----------------Inventory & Order Management System----

---Create Products Table----
CREATE TABLE products (
    product_id NUMBER PRIMARY KEY,
    product_name VARCHAR2(100),
    category VARCHAR2(50),
    price NUMBER(10,2),
    stock_quantity NUMBER,
    reorder_level NUMBER
);

--------------Create Customers Table----------
CREATE TABLE i_customers (
    customer_id NUMBER PRIMARY KEY,
    customer_name VARCHAR2(100),
    city VARCHAR2(50)
);

-------Create Orders Table------
CREATE TABLE orders (
    order_id NUMBER PRIMARY KEY,
    customer_id NUMBER,
    order_date DATE,
    total_amount NUMBER(12,2),
    CONSTRAINT fk_customer1 FOREIGN KEY (customer_id) REFERENCES i_customers(customer_id)
);

-----Create Order Details Table----
CREATE TABLE order_details (
    order_detail_id NUMBER PRIMARY KEY,
    order_id NUMBER,
    product_id NUMBER,
    quantity NUMBER,
    amount NUMBER(12,2),

    CONSTRAINT fk_order
    FOREIGN KEY (order_id)
    REFERENCES orders(order_id),

    CONSTRAINT fk_product
    FOREIGN KEY (product_id)
    REFERENCES products(product_id)
);

-------Create Inventory Audit Table-----
CREATE TABLE inventory_audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_id NUMBER,
    old_stock NUMBER,
    new_stock NUMBER,
    action_date DATE
);

-----Insert Sample Data---
INSERT INTO products VALUES (101,'Laptop','Electronics',55000,20,5);
INSERT INTO products VALUES (102,'Mouse','Electronics',500,100,20);
INSERT INTO i_customers VALUES (1,'Arjun Kumar','Patna');
COMMIT;


----Trigger for Automatic Stock Deduction-----
CREATE OR REPLACE TRIGGER trg_stock_deduction
AFTER INSERT
ON order_details
FOR EACH ROW
BEGIN

    UPDATE products
    SET stock_quantity = stock_quantity - :NEW.quantity
    WHERE product_id = :NEW.product_id;

END;

-----------------Trigger for Inventory Audit Logging--------
CREATE OR REPLACE TRIGGER trg_inventory_audit
AFTER UPDATE OF stock_quantity
ON products
FOR EACH ROW
BEGIN

    INSERT INTO inventory_audit (
        product_id,
        old_stock,
        new_stock,
        action_date
    )
    VALUES (
        :NEW.product_id,
        :OLD.stock_quantity,
        :NEW.stock_quantity,
        SYSDATE
    );

END;

----------------Function to Check Available Stock---------
CREATE OR REPLACE FUNCTION check_stock (
    p_product_id NUMBER
)
RETURN NUMBER
IS

    v_stock NUMBER;

BEGIN

    SELECT stock_quantity
    INTO v_stock
    FROM products
    WHERE product_id = p_product_id;

    RETURN v_stock;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;

END;

-----------------Package Specification-----------
CREATE OR REPLACE PACKAGE inventory_package
IS

    PROCEDURE create_order (
        p_order_id NUMBER,
        p_customer_id NUMBER
    );

    PROCEDURE add_order_item (
        p_order_detail_id NUMBER,
        p_order_id NUMBER,
        p_product_id NUMBER,
        p_quantity NUMBER
    );

    PROCEDURE generate_sales_report;

    PROCEDURE low_stock_report;

END inventory_package;

------------Package Body-------------
CREATE OR REPLACE PACKAGE BODY inventory_package
IS

    ------------------------------------------------
    -- Create Order
    ------------------------------------------------

    PROCEDURE create_order (
        p_order_id NUMBER,
        p_customer_id NUMBER
    )
    IS
    BEGIN

        INSERT INTO orders (
            order_id,
            customer_id,
            order_date,
            total_amount
        )
        VALUES (
            p_order_id,
            p_customer_id,
            SYSDATE,
            0
        );

        COMMIT;

        DBMS_OUTPUT.PUT_LINE('Order Created Successfully');

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            DBMS_OUTPUT.PUT_LINE(SQLERRM);

    END create_order;

    ------------------------------------------------
    -- Add Order Item
    ------------------------------------------------

    PROCEDURE add_order_item (
        p_order_detail_id NUMBER,
        p_order_id NUMBER,
        p_product_id NUMBER,
        p_quantity NUMBER
    )
    IS

        v_price NUMBER;
        v_stock NUMBER;
        v_amount NUMBER;

    BEGIN

        SELECT price, stock_quantity
        INTO v_price, v_stock
        FROM products
        WHERE product_id = p_product_id;

        IF v_stock < p_quantity THEN

            RAISE_APPLICATION_ERROR(
                -20001,
                'Insufficient Stock'
            );

        END IF;

        v_amount := v_price * p_quantity;

        INSERT INTO order_details (
            order_detail_id,
            order_id,
            product_id,
            quantity,
            amount
        )
        VALUES (
            p_order_detail_id,
            p_order_id,
            p_product_id,
            p_quantity,
            v_amount
        );

        UPDATE orders
        SET total_amount = total_amount + v_amount
        WHERE order_id = p_order_id;

        COMMIT;

        DBMS_OUTPUT.PUT_LINE('Order Item Added');

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            DBMS_OUTPUT.PUT_LINE(SQLERRM);

    END add_order_item;

    ------------------------------------------------
    -- Sales Report Using Cursor
    ------------------------------------------------

    PROCEDURE generate_sales_report
    IS

        CURSOR c_sales IS
        SELECT p.product_name,
               SUM(od.quantity) total_qty,
               SUM(od.amount) total_sales
        FROM products p
        JOIN order_details od
        ON p.product_id = od.product_id
        GROUP BY p.product_name
        ORDER BY total_sales DESC;

        v_name products.product_name%TYPE;
        v_qty NUMBER;
        v_sales NUMBER;

    BEGIN

        OPEN c_sales;

        LOOP

            FETCH c_sales
            INTO v_name,
                 v_qty,
                 v_sales;

            EXIT WHEN c_sales%NOTFOUND;

            DBMS_OUTPUT.PUT_LINE(
                'Product : ' || v_name ||
                ' | Quantity Sold : ' || v_qty ||
                ' | Sales : ' || v_sales
            );

        END LOOP;

        CLOSE c_sales;

    END generate_sales_report;

    ------------------------------------------------
    -- Low Stock Report
    ------------------------------------------------

    PROCEDURE low_stock_report
    IS
    BEGIN

        FOR rec IN (
            SELECT product_name,
                   stock_quantity,
                   reorder_level
            FROM products
            WHERE stock_quantity <= reorder_level
        )
        LOOP

            DBMS_OUTPUT.PUT_LINE(
                'Low Stock Alert -> ' ||
                rec.product_name ||
                ' | Stock : ' || rec.stock_quantity
            );

        END LOOP;

    END low_stock_report;

END inventory_package;


---------------------Dynamic SQL Example-------------
DECLARE

    v_sql VARCHAR2(200);

BEGIN

    v_sql :=
    'UPDATE products
     SET price = price + 100
     WHERE category = ''Electronics''';

    EXECUTE IMMEDIATE v_sql;

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Prices Updated Successfully');

END;

---------Create Indexes for Performance-----
CREATE INDEX idx_product_category
ON products(category);

CREATE INDEX idx_order_customer
ON orders(customer_id);

----testing -----------------
--Create Order
BEGIN
   inventory_package.create_order(1001,1);
END;
---Add Order Item
BEGIN
    inventory_package.add_order_item(1,1001,101,2);
END;

----Generate Sales Report
BEGIN
    inventory_package.generate_sales_report;
END;
---Low Stock Report
BEGIN
    inventory_package.low_stock_report;
END;

---Analytical Query Example
SELECT
    product_name,
    SUM(amount) total_sales,
    RANK() OVER (
        ORDER BY SUM(amount) DESC
    ) sales_rank
FROM products p
JOIN order_details od
ON p.product_id = od.product_id
GROUP BY product_name;

----View Tables
SELECT * FROM products;
SELECT * FROM orders;
SELECT * FROM order_details;

SELECT * FROM inventory_audit;
